networks:
  app_network:
    driver: bridge

services:
  
  db:
    image: mysql:5.7
    env_file:
      - .env 
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"  # Utilisation de la variable d'environnement
    networks:
      - app_network

  django:
    build:
      context: ./DB_Api_Docker/C2V2
    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"
    depends_on:
      - db
    env_file:
      - .env  
    networks:
      - app_network

  planes_api:
    build:
      context: ./DB_Api_Docker/planes
    ports:
      - "${EXTERNAL_PORT_PLANE_API}:${INTERNAL_PORT_API}"
    depends_on:
      - db
      - django
    env_file:
      - .env  
    networks:
      - app_network

  ships_api:
    build:
      context: ./DB_Api_Docker/ships
    ports:
      - "${EXTERNAL_PORT_SHIP_API}:${INTERNAL_PORT_API}"
    depends_on:
      - db
      - django
    env_file:
      - .env 
    networks:
      - app_network

  frontend:
    build:
      context: ./Website_server/src
    depends_on:
      - db
      - django
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    env_file:
      - .env 
    volumes: 
      - ./Website_server/src/C_and_C/static:/app/C_and_C/static  # Monter C_and_C/static depuis le répertoire local
      - ./Website_server/src/accounts/static:/app/accounts/static  # Monter accounts/static depuis le répertoire local
    networks:
      - app_network
