services:
  db:
    image: mysql:5.7  
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"  

  web:
    build:
      context: ./DB_Api_Docker/C2V2
    container_name: django_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306  # Connexion MySQL dans le conteneur avec le port interne 3306
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword


  python_service_1:
    build:
      context: ./DB_Api_Docker/planes
    container_name: planes
    depends_on:
      - db
      - web
    environment:
      DJANGO_API_URL: http://web:8080
      DB_HOST: db
      DB_PORT: 3306  # Connexion MySQL dans le conteneur avec le port interne 3306
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword


  python_service_2:
    build:
      context: ./DB_Api_Docker/ships
    container_name: ships
    depends_on:
      - db
      - web
    environment:
      DJANGO_API_URL: http://web:8080
      DB_HOST: db
      DB_PORT: 3306  # Connexion MySQL dans le conteneur avec le port interne 3306
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword


  frontend:
    build:
      context: ./Website_server/src
    container_name: webserver
    depends_on:
      - db
      - web
    environment:
      DJANGO_API_URL: http://web:8080
      DB_HOST: db
      DB_PORT: 3306  # Connexion MySQL dans le conteneur avec le port interne 3306
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
