# Generated by Django 5.1.3 on 2024-11-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('entity_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Plane', 'Plane'), ('Ship', 'Ship'), ('LandForce', 'LandForce'), ('User', 'User')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'entities',
            },
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('enemy', models.BooleanField()),
                ('time_position', models.DateTimeField()),
                ('geo_altitude', models.IntegerField()),
                ('velocity', models.IntegerField()),
                ('true_track', models.IntegerField()),
                ('call_sign', models.CharField(max_length=255)),
                ('origin_country', models.CharField(max_length=255)),
                ('on_ground', models.BooleanField()),
                ('category', models.IntegerField()),
                ('size', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'plane',
            },
        ),
    ]
