# Generated by Django 5.1.3 on 2024-11-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='enemy',
            field=models.IntegerField(),
        ),
    ]
