# Generated by Django 5.1.3 on 2024-11-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entities',
            fields=[
                ('entity_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Plane', 'Plane'), ('Ship', 'Ship'), ('LandForce', 'LandForce'), ('User', 'User')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'entities',
            },
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='tutorial',
            name='longitude',
        ),
    ]
