# Generated by Django 5.1.3 on 2024-11-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_entities_remove_tutorial_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutorial',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
