# Generated by Django 5.1.3 on 2024-11-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_alter_tutorial_enemy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='on_ground',
            field=models.IntegerField(),
        ),
    ]
