# Generated by Django 5.1.3 on 2024-11-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_tutorial_latitude_tutorial_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='enemy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='geo_altitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='on_ground',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='true_track',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='velocity',
            field=models.FloatField(),
        ),
    ]
