# Generated by Django 5.1.3 on 2024-11-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_alter_tutorial_on_ground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='time_position',
            field=models.CharField(max_length=255),
        ),
    ]
