# Generated by Django 5.1.3 on 2024-11-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_tutorial_entry_id_alter_tutorial_time_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='id',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='plane_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
